const baseurl=   'https://github.com/KSHITIJ-2022/media/blob/master/images/'

let getImageUrl=(type,image)=>{
    return baseurl+type+'/'+image+'?raw=true'
}
export default function data() {

    const web = [
        // {
        //     name: "Tarun Tej Thadana",
        //     email: "taruntejthadana@gmail.com",
        //     phone: "7993884462",
        //     linkedin: "https://www.linkedin.com/in/tarun-tej-thadana-3b89b91a5",
        //     facebook: "https://m.facebook.com/tarun.tej.96?refsrc=deprecated&_rdr",
        //     post: "Tech Team Head",
        //     image: getImageUrl('Tech','Tarun-Tej-Thadana.png'),
        // },
        // {
        //     name: "Aditya Agrawal",
        //     email: "adityaag121@gmail.com",
        //     phone: "7071806413",
        //     linkedin: "https://www.linkedin.com/in/aditya-agrawal-a8a71a189",
        //     facebook: "https://www.facebook.com/adityaagrawal.99",
        //     post: "Tech Team Head",
        //     image: getImageUrl('Tech','Aditya-Agrawal.png'),
        // },
        // {
        //     name: "Kavita Kakar",
        //     email: "kavita.gsphk@gmail.com",
        //     phone: "7602255111",
        //     linkedin: "https://www.linkedin.com/in/kavita-kakar-b7a4b3194/",
        //     facebook: "https://www.facebook.com/kavita.kakar.18",
        //     post: "Tech Team Head",
        //     image:  getImageUrl('Tech','Kavita-Kakkar.png'),
        // },
        // {
        //     name: "Ankit Kumar Sahoo",
        //     email: "10ankitkusahoo10@gmail.com",
        //     phone: "7008521348",
        //     linkedin: "https://www.linkedin.com/in/ankit-kumar-sahoo",
        //     facebook: "https://m.facebook.com/profile.php?id=100004762007835",
        //     post: "Tech Team Head",
        //     image: getImageUrl('Tech','Ankit-Kumar-Sahoo.png'),
        // },
        // {
        //     name: "Shrinish Vhanbatte",
        //     email: "shrinishiitkgp2001@gmail.com",
        //     phone: "7350032932",
        //     linkedin: "https://in.linkedin.com/in/shrinish-vhanbatte-972b11193",
        //     facebook: "https://www.facebook.com/shrinish.vhanbatte.7",
        //     post: "Tech Team Head",
        //     image:getImageUrl('Tech','Shrinish-Vhanbatte.png'),
        // },
        // {
        //     name: "Chitesh Bansal",
        //     email: "chiteshbansal111@gmail.com",
        //     phone: "9416343518",
        //     linkedin: "https://www.linkedin.com/in/chitesh-bansal-00754a191/",
        //     facebook: "https://www.facebook.com/chitesh.bansal.75",
        //     post: "Tech Team Head",
        //     image:getImageUrl('Tech','Chitesh-Bansal.png'),
        // },
    ]
    const coredata = [
        // {
        //     name: "Gaurav Kumar",
        //     email: "gaurav.kumar@ktj.in",
        //     phone: "9350031637",
        //     linkedin: "https://www.linkedin.com/in/gaurav-kumar-1616981a1/",
        //     facebook: "https://www.facebook.com/profile.php?id=100032656905882",
        //     post: "Executive Head",
        //     image: getImageUrl('Core','Gaurav-Kumar.png'),
        // },
        // {
        //     name: "Vadthya Sanjay Kumar",
        //     email: "vadthya.sanjay@ktj.in",
        //     phone: "9121372359",
        //     linkedin: "https://www.linkedin.com/in/vadthya-sanjay-kumar-8962591b6/",
        //     facebook: "https://www.facebook.com/sanjay.naik.16121471/",
        //     post: "Executive Head",
        //     image: getImageUrl('Core','Vadthya-Sanjay-Kumar.png'),
        // },
        // {
        //     name: "Zeel Patel",
        //     email: "zeel.patel@ktj.in",
        //     phone: "9426856970",
        //     linkedin: "https://www.linkedin.com/in/zeel-patel-2450371b6/",
        //     facebook: "https://www.facebook.com/profile.php?id=100038044820011",
        //     post: "Finance Head and Exhibition Coordinator",
        //     image: getImageUrl('Core','Zeel-Patel.png'),
        // },
        // {
        //     name: "Kartikeya Maich",
        //     email: "kartikeya.m@ktj.in",
        //     phone: "9602959210",
        //     linkedin: "https://www.linkedin.com/in/kartikeya-maich-11b7541b7",
        //     facebook: "https://www.facebook.com/kartikeya.maich",
        //     post: "Sponsorship Head",
        //     image: getImageUrl('Core','Kartikeya-Maich.png'),
        // },
        // {
        //     name: "Sahil Dhamore",
        //     email: "sahil.dhamore@ktj.in",
        //     phone: "9111177602",
        //     linkedin: "https://www.linkedin.com/in/sahil-dhamore-0897501a0/",
        //     facebook: "https://www.facebook.com/profile.php?id=100008577945307",
        //     post: "Sponsorship Head",
        //     image: getImageUrl('Core','Sahil-Dhamore.png'),
        // },
        // {
        //     name: "Himabindu Matta ",
        //     email: "himabindu.matta@ktj.in",
        //     phone: "9515459939",
        //     linkedin: "https://www.linkedin.com/in/himabindu-matta-4320681aa",
        //     facebook: "https://www.facebook.com/himabindu.matta.9",
        //     post: "Sponsorship Head",
        //     image: getImageUrl('Core','Himabindu.png'),
        // },
        // {
        //     name: "Sreeya Chidere",
        //     email: "sreeya.chidere@ktj.in",
        //     phone: "8897959675",
        //     linkedin: "https://www.linkedin.com/mwlite/in/sreeya-chidere-16b7491b6",
        //     facebook: "https://m.facebook.com/100008377784187/",
        //     post: "Sponsorship Head",
        //     image: getImageUrl('Core','Sreeya-Chidere.png'),
        // },
        // {
        //     name: "Ayush Surana",
        //     email: "ayush.surana@ktj.in",
        //     phone: "8602090470",
        //     linkedin: "https://www.linkedin.com/in/ayush-surana-6671631b1",
        //     facebook: "https://m.facebook.com/100011340189422/",
        //     post: "Sponsorship Head and Exhibition Coordinator",
        //     image: getImageUrl('Core','Ayush-Surana.png'),
        // },
        // {
        //     name: "Sairam Reddy Kannareddy",
        //     email: "sairam.kanna@ktj.in",
        //     phone: "7995458560",
        //     linkedin: "https://www.linkedin.com/in/sairam-reddy-kannareddy-8488951b5",
        //     facebook: "https://www.facebook.com/sairamreddy.kannareddy",
        //     post: "Events Head",
        //     image: getImageUrl('Core','Sairam-Reddy-K.png'),
        // },
        // {
        //     name: "Abhishek Kumar",
        //     email: "abhishek.kumartrn@ktj.in",
        //     phone: "8002131381",
        //     linkedin: " https://www.linkedin.com/in/abhishek-kumar-6193321b6",
        //     facebook: "https://www.facebook.com/abhishek.k.tarun",
        //     post: "Events Head and Website Coordinator",
        //     image: getImageUrl('Core','Abhishek-Kumar.png'),
        // },
        // {
        //     name: "Abhinav Khare",
        //     email: "abhinav.Khare@ktj.in",
        //     phone: "9425112465",
        //     linkedin: "linkedin.com/in/abhinav-khare-4bab36199",
        //     facebook: "https://m.facebook.com/abhinav.khare.56",
        //     post: "Events Head",
        //     image: getImageUrl('Core','Abhinav-Khare.png'),
        // },
        // {
        //     name: "Vishnu Kumar",
        //     email: "vishnu.kanwat@ktj.in",
        //     phone: "9549468315",
        //     linkedin: "https://www.linkedin.com/in/vishnu-kanwat-90485b1b6",
        //     facebook: "https://www.facebook.com/vishu3908",
        //     post: "Events Head",
        //     image: getImageUrl('Core','Vishnu.png'),
        // },
        // {
        //     name: "Sudhanshu Ranjan",
        //     email: "ranjan.sudhanshu@ktj.in",
        //     phone: "7586885333",
        //     linkedin: "https://www.linkedin.com/in/sudhanshu-ranjan-075b0b196",
        //     facebook: "https://www.facebook.com/profile.php?id=100024961320497",
        //     post: "Events Head",
        //     image: getImageUrl('Core','Sudhanshu-Ranjan.png'),
        // },
        // {
        //     name: "Kodi Shree Harsha",
        //     email: "shreeharsha.k@ktj.in",
        //     phone: "7479238088",
        //     linkedin: "https://www.linkedin.com/in/shree-harsha-kodi-3212461b6/",
        //     facebook: "https://www.facebook.com/shreeharsha123",
        //     post: "Publicity Head and Design Coordinator",
        //     image: getImageUrl('Core','Shree-Harsha.png'),
        // },
        // {
        //     name: "Shubham Saurav",
        //     email: "ss.saurav@ktj.in",
        //     phone: "7667457991",
        //     linkedin: "https://www.linkedin.com/in/shubham-saurav-68a6771aa/",
        //     facebook: "https://www.facebook.com/shubham.saurav.106",
        //     post: "Publicity Head and Design Coordinator",
        //     image: getImageUrl('Core','Shubham-Saurav.png'),
        // },
    ]
    const designdata = [
        // {
        //     name: "Sharvari Sriram ",
        //     email: "sharvari.sriram26@gmail.com",
        //     phone: "9769080263",
        //     linkedin: "https://www.linkedin.com/in/sharvari-sriram-9b543b1b3/",
        //     facebook: "https://www.facebook.com/sharvari.sriram",
        //     post: "Design Team Head",
        //     image: getImageUrl('Design','Sharvari-Sriram.png'),
        // },
        // {
        //     name: "Harshavardhan Putta",
        //     email: "harshavardhanputta5@gmail.com",
        //     phone: "8978707443",
        //     linkedin: "",
        //     facebook: "https://www.facebook.com/profile.php?id=100040884662231",
        //     post: "Design Team Head",
        //     image: getImageUrl('Design','Harshavardhan-Putta.png'),
        // },
        // {
        //     name: "Charmisha Gedela ",
        //     email: "charmishagedela@gmail.com ",
        //     phone: "9734182011",
        //     linkedin: "https://www.linkedin.com/in/charmisha-gedela-7141a5204/",
        //     facebook: "https://www.facebook.com/charmisha.gedela",
        //     post: "Design Team Head",
        //     image: getImageUrl('Design','Charmisha-Gadela.png'),
        // },
        // {
        //     name: "Shalmali Sriram ",
        //     email: "shalmali.sriram26@gmail.com",
        //     phone: "9833327010",
        //     linkedin: "https://www.linkedin.com/in/shalmali-sriram-38743b1b3/",
        //     facebook: "https://www.facebook.com/shalmali.sriram",
        //     post: "Design Team Head",
        //     image: getImageUrl('Design','Shalmali-Sriram.png'),
        // },
        // {
        //     name: "Renu Sree Pinninti ",
        //     email: "pinnintirenusree0630@gmail.com",
        //     phone: "7780744049",
        //     linkedin: "https://www.linkedin.com/in/renu-sree-pinninti-a14781191/",
        //     facebook: "https://www.facebook.com/renusree.pinninti",
        //     post: "Design Team Head",
        //     image: getImageUrl('Design','Renu-Sree-Pinninti.png'),
        // },
        // {
        //     name: "Ankit Pal",
        //     email: "pal.ankit.6762@gmail.com",
        //     phone: "9971845223",
        //     linkedin: "https://www.linkedin.com/in/ankitpal21/",
        //     facebook: "https://www.facebook.com/profile.php?id=100011445711368",
        //     post: "Design Team Head",
        //     image: getImageUrl('Design','Ankit-Pal.png'),
        // },
        // {
        //     name: "Abhinav M",
        //     email: "1289nav@gmail.com ",
        //     phone: "8296088706",
        //     linkedin: "https://www.linkedin.com/in/abhinav-sachin-848ba01b2/",
        //     facebook: "https://www.facebook.com/abhinav.sachin.92",
        //     post: "Design Team Head",
        //     image: getImageUrl  ('Design','Abhinav-M.png'),
        // },
        // {
        //     name: "Nihar Domala",
        //     email: "nihardomala@gmail.com",
        //     phone: "9014549044",
        //     linkedin: "https://www.linkedin.com/in/nihar-domala/",
        //     facebook: "https://www.facebook.com/NiharDomala",
        //     post: "Design Team Head",
        //     image: getImageUrl('Design','Nihar-DOmala.png'),
        // },
    ]
    return { web, coredata, designdata };
}
