/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, Sparkles } from "@react-three/drei";

export function SpaceshipPC(props) {
  const { nodes, materials } = useGLTF("/models/spaceship_pc_comp/model.gltf");
  const [click, setClick] = useState(0);
  const handleEasterClick = () => {
    if (click === 1) {
      setClick(0);
      window.open("https://ipash185.github.io/RetroPix/", "_blank");
    }
    else {
      setClick(click+1);
    }
    
  };
  return (
    <group {...props} dispose={null} position={[-0.3, -2, -15]}>
    <Sparkles count={2000} scale={[20, 20, 30]} size={1.5} speed={2} position={[0, 1.385, 0]} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["1inner002"].geometry}
        material={materials["Material.005"]}
        position={[-3.345, 1.385, -2.805]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={3.357}
        onClick={handleEasterClick}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2outer002"].geometry}
        material={materials["Material.001"]}
        position={[-3.345, 1.385, -2.805]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[3.357, 2.987, 3.357]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0028"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.256, 3.943, -2.974]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0029"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.256, 5.871, -2.974]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0030"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.256, 5.885, -2.974]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0031"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.256, 3.94, -2.974]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0032"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.247, 5.897, -2.989]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0033"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.247, 3.94, -2.989]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Black_Ground_Black_0005.geometry}
        material={materials["Black.001"]}
        position={[-2.012, 5.087, 0.108]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011580"].geometry}
        material={materials["Black-Wall.003"]}
        position={[0.373, 10.539, -22.503]}
        rotation={[0, -1.176, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011581"].geometry}
        material={materials["Black-Wall.003"]}
        position={[-10.73, 10.539, -3.909]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011583"].geometry}
        material={materials["Black-Wall.003"]}
        position={[-9.975, 10.539, -19.548]}
        rotation={[0, -0.603, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011584"].geometry}
        material={materials["Black-Wall.003"]}
        position={[-19.13, 10.541, -2.176]}
        rotation={[0, 0.459, 0]}
        scale={0.01}
      />
      <group
        position={[19.49, 10.539, -0.589]}
        rotation={[Math.PI, -0.278, Math.PI]}
        scale={0.01}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_011685"].geometry}
          material={materials["Black-Wall.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_011685_1"].geometry}
          material={materials.Emissive_Cyan__0}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011586"].geometry}
        material={materials["Black-Wall.003"]}
        position={[11.125, 10.539, -19.041]}
        rotation={[Math.PI, -1.369, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011587"].geometry}
        material={materials["Black-Wall.003"]}
        position={[-7.493, 10.539, 14.864]}
        rotation={[-Math.PI, 1.559, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011588"].geometry}
        material={materials["Black-Wall.003"]}
        position={[7.661, 10.539, 15.001]}
        rotation={[-Math.PI, 0.784, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011593"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 4.287, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011594"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 4.287, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011595"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 4.287, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011596"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.215, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011597"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.215, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011598"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.215, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011599"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.229, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011600"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.229, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011601"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.229, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011602"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.215, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011603"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.215, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011604"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 4.284, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011605"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 4.284, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011606"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 4.284, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011607"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.087, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011608"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 4.286, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011609"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.234, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011610"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 6.221, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011611"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 4.271, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011612"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 4.284, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011615"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 6.241, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011616"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 6.241, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011617"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 6.241, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011618"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 6.241, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011619"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 6.241, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011620"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 4.284, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011621"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 4.284, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011622"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 4.284, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011623"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 4.284, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011624"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 4.284, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials["Material.002"]}
        position={[0.176, 0, -3.218]}
        scale={19.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Emissive_Cyan__0313.geometry}
        material={materials.Emissive_Cyan__0}
        position={[7.908, 5.97, 14.946]}
        rotation={[-Math.PI, 1.165, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Emissive_Cyan__0314.geometry}
        material={materials.Emissive_Cyan__0}
        position={[10.98, 6.384, -19.2]}
        rotation={[Math.PI, -0.937, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Emissive_Cyan__0315.geometry}
        material={materials.Emissive_Cyan__0}
        position={[-10.148, 5.97, -19.573]}
        rotation={[-Math.PI, 0.987, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Emissive_Cyan__0317.geometry}
        material={materials.Emissive_Cyan__0}
        position={[-19.144, 5.97, -1.93]}
        rotation={[0, 0.07, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Emissive_Cyan__0318.geometry}
        material={materials.Emissive_Cyan__0}
        position={[-7.277, 5.97, 14.994]}
        rotation={[0, 1.186, -Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Emissive_Cyan__0319.geometry}
        material={materials["Emissive_Cyan__0.001"]}
        position={[-0.874, 1.075, -1.463]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor001_M_Floor_001_0009.geometry}
        material={materials["M_Floor_001.002"]}
        position={[-5.241, -0.572, 49.683]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor002_M_Floor_001_0009.geometry}
        material={materials["M_Floor_001.002"]}
        position={[-5.241, -0.572, 38.277]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor003_M_Floor_002_0009.geometry}
        material={materials["M_Floor_002.002"]}
        position={[-5.241, -0.572, 26.871]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor011_M_Ceiling_003_0009.geometry}
        material={materials["M_Ceiling_003.002"]}
        position={[-5.241, 10.834, 15.464]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor013_M_Ceiling_002_0009.geometry}
        material={materials["M_Ceiling_002.002"]}
        position={[-5.241, 10.834, 26.871]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor014_M_Ceiling_002_0009.geometry}
        material={materials["M_Ceiling_002.002"]}
        position={[-5.241, 10.834, 38.277]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor015_M_Ceiling_002_0010.geometry}
        material={materials["M_Ceiling_002.002"]}
        position={[-5.241, 10.834, 49.683]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor_M_Floor_001_0010.geometry}
        material={materials["M_Floor_001.002"]}
        position={[-5.241, -0.572, 61.089]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <pointLight
        intensity={6.729}
        decay={2}
        color="#77bcff"
        position={[-10.786, 4.403, -11.918]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={30}
        decay={2.5}
        color="#77bcff"
        position={[0, 2, 0]}
      />
      {/* <spotLight
        intensity={3}
        decay={1}
        color="#77bcff"
        position={[0, 2, 4]}
        penumbra={1}
      /> */}
      {/* <pointLight
        intensity={2.5}
        decay={1}
        color="#77bcff"
        position={[4, -1, 18]}
      />
      <pointLight
        intensity={2.5}
        decay={1}
        color="#77bcff"
        position={[-2, -1, 18]}
      /> */}
      <pointLight
        intensity={6.729}
        decay={2}
        color="#77bcff"
        position={[-8.796, 4.403, 5.326]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={6.729}
        decay={2}
        color="#77bcff"
        position={[11.763, 4.403, 4.073]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={6.729}
        decay={2}
        color="#77bcff"
        position={[9.773, 4.403, -12.065]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <group position={[0.257, 0, -2.983]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Black_LightUpper_Black-Upper_0006"].geometry}
            material={materials["Black-Upper.001"]}
            position={[-226.264, 508.734, 303.999]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Emissive_Red_Emissive-Red_0005"].geometry}
            material={materials["Emissive-Red.001"]}
            position={[4.632, 438.369, 303.999]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Light_Upper_Light-Upper_0006"].geometry}
            material={materials["Light-Upper.001"]}
            position={[-461.792, 451.184, 32.134]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Supports001_M_Supports_0009.geometry}
        material={materials["M_Supports.002"]}
        position={[0.287, 5.131, 38.277]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[5.528, 5.703, 5.703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Supports002_M_Supports_0009.geometry}
        material={materials["M_Supports.002"]}
        position={[0.287, 5.131, 26.871]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[5.528, 5.703, 5.703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Supports_M_Supports_0009.geometry}
        material={materials["M_Supports.002"]}
        position={[0.287, 5.131, 49.683]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[5.528, 5.703, 5.703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall001_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[-5.241, -0.572, 49.683]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall002_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[-5.241, -0.572, 38.277]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall003_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[-5.241, -0.572, 26.871]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall004_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[5.815, -0.572, 15.464]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall005_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[5.815, -0.572, 26.871]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall006_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[5.815, -0.572, 38.277]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall007_M_Wall_0010.geometry}
        material={materials["M_Wall.003"]}
        position={[5.815, -0.572, 49.683]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 28.515]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_M_Wall_0010.geometry}
        material={materials["M_Wall.003"]}
        position={[-5.241, -0.572, 61.089]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[27.639, 28.515, 28.515]}
      />
    </group>
  );
}
