/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF, Sparkles } from "@react-three/drei";

export function SpaceshipMobile({isVR}) {
  const { nodes, materials } = useGLTF("/models/spaceship_phone_comp/model.gltf");
  const [click, setClick] = useState(0);
  const handleEasterClick = () => {
    if (click === 1) {
      setClick(0);
      window.open("https://ipash185.github.io/RetroPix/", "_blank");
    }
    else {
      setClick(click+1);
    }
    
  };
  return (
    <group dispose={null} position={[-0.25, -15, -10]}>
    <Sparkles count={500} scale={[20, 20, 30]} size={1.5} speed={2} position={[0, 13.32, 0]} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["1inner002"].geometry}
        material={materials["Material.005"]}
        position={isVR ? [4.5, 14.5, 12] : [-3.844, 13.32, -2.99]}
        rotation={isVR ? [Math.PI / 2, 0, Math.PI] : [Math.PI / 2, 0, 0]}
        scale={3.863}
        onClick={handleEasterClick}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["2outer002"].geometry}
        material={materials["Material.001"]}
        position={isVR ? [4.5, 14.5, 12] : [-3.845, 13.322, -2.988]}
        rotation={isVR ? [Math.PI / 2, 0, Math.PI] : [Math.PI / 2, 0, 0]}
        scale={[3.863, 3.437, 3.863]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0028"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.256, 4.794, -2.974]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0029"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.256, 18.737, -2.974]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0030"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.256, 18.751, -2.974]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0031"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.256, 4.791, -2.974]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0032"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.247, 18.763, -2.989]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["3_Wall_Hori_1__0033"].geometry}
        material={materials.Emissive_Cyan__0}
        position={[0.247, 4.791, -2.989]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Black_Ground_Black_0005.geometry}
        material={materials["Black.001"]}
        position={[-2.012, 5.087, 0.108]}
        scale={0.01}
      />
      <group
        position={[-9.969, 30.2, -19.475]}
        rotation={[0, -0.604, 0]}
        scale={[0.011, 0.028, 0.011]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0002_1"].geometry}
          material={materials["Black-Wall.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0002_2"].geometry}
          material={materials.Emissive_Cyan__0}
        />
      </group>
      <group
        position={[7.75, 30.2, 14.915]}
        rotation={[-Math.PI, 0.785, -Math.PI]}
        scale={[0.011, 0.028, 0.011]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0003_1"].geometry}
          material={materials["Black-Wall.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0003_2"].geometry}
          material={materials.Emissive_Cyan__0}
        />
      </group>
      <group
        position={[-19.131, 30.2, -2.07]}
        rotation={[0, 0.463, 0]}
        scale={[0.011, 0.028, 0.011]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0004_1"].geometry}
          material={materials["Black-Wall.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0004_2"].geometry}
          material={materials.Emissive_Cyan__0}
        />
      </group>
      <group
        position={[-7.612, 30.2, 14.876]}
        rotation={[0, 1.571, 0]}
        scale={[0.011, 0.028, 0.011]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0005_1"].geometry}
          material={materials["Black-Wall.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0005_2"].geometry}
          material={materials.Emissive_Cyan__0}
        />
      </group>
      <group
        position={[11.131, 30.2, -19.075]}
        rotation={[Math.PI, -1.344, Math.PI]}
        scale={[0.011, 0.028, 0.011]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0006_1"].geometry}
          material={materials["Black-Wall.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_0006_2"].geometry}
          material={materials.Emissive_Cyan__0}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011580"].geometry}
        material={materials["Black-Wall.003"]}
        position={[0.373, 10.539, -22.503]}
        rotation={[0, -1.176, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011581"].geometry}
        material={materials["Black-Wall.003"]}
        position={[-10.73, 10.539, -3.909]}
        scale={0.01}
      />
      <group
        position={[19.426, 30.2, -0.564]}
        rotation={[Math.PI, -0.278, Math.PI]}
        scale={[0.011, 0.028, 0.011]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_011685"].geometry}
          material={materials["Black-Wall.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Black_Wall_Black-Wall_011685_1"].geometry}
          material={materials.Emissive_Cyan__0}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011593"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.124, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011594"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.138, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011595"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.129, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011596"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 19.081, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011597"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 19.081, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011598"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 19.081, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011599"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 19.095, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011600"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 19.095, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011601"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 19.095, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011602"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 26.377, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011603"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 26.384, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011604"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.135, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011605"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.135, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011606"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.135, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011607"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.137, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011608"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.137, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011609"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 24.647, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011610"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 24.647, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011611"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.122, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011612"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.006, 5.123, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011615"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 19.107, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011616"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 19.107, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011617"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 19.107, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011618"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 31.956, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011619"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 31.93, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011620"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 5.135, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011621"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 5.135, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011622"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 5.135, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011623"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 5.134, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Black_Wall_Black-Wall_011624"].geometry}
        material={materials["Black-Wall"]}
        position={[-2.097, 5.135, -5.966]}
        rotation={[Math.PI, -1.307, Math.PI]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials["Material.003"]}
        position={[0.176, 0, -3.218]}
        scale={19.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Emissive_Cyan__0314.geometry}
        material={materials.Emissive_Cyan__0}
        position={[10.98, 6.384, -19.2]}
        rotation={[Math.PI, -0.937, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Emissive_Cyan__0319.geometry}
        material={materials["Emissive_Cyan__0.001"]}
        position={[-0.874, 1.075, -1.463]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor001_M_Floor_001_0009.geometry}
        material={materials["M_Floor_001.002"]}
        position={[-5.241, 6.497, 49.683]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor002_M_Floor_001_0009.geometry}
        material={materials["M_Floor_001.002"]}
        position={[-5.241, 6.497, 38.277]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor003_M_Floor_002_0009.geometry}
        material={materials["M_Floor_002.002"]}
        position={[-5.241, 6.497, 26.871]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor011_M_Ceiling_003_0009.geometry}
        material={materials["M_Ceiling_003.002"]}
        position={[-5.241, 22.341, 15.464]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor013_M_Ceiling_002_0009.geometry}
        material={materials["M_Ceiling_002.002"]}
        position={[-5.241, 22.341, 26.871]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor014_M_Ceiling_002_0009.geometry}
        material={materials["M_Ceiling_002.002"]}
        position={[-5.241, 22.341, 38.277]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor015_M_Ceiling_002_0010.geometry}
        material={materials["M_Ceiling_002.002"]}
        position={[-5.241, 22.341, 49.683]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floor_M_Floor_001_0010.geometry}
        material={materials["M_Floor_001.002"]}
        position={[-5.241, 6.497, 61.089]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      {/* <pointLight
        intensity={5.729}
        decay={2}
        color="#77bcff"
        position={[-10.786, 11.942, -11.918]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={5.729}
        decay={2}
        color="#77bcff"
        position={[-8.796, 11.942, 5.326]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={5.729}
        decay={2}
        color="#77bcff"
        position={[11.763, 11.942, 4.073]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={5.729}
        decay={2}
        color="#77bcff"
        position={[9.773, 11.942, -12.065]}
        rotation={[-Math.PI / 2, 0, 0]}
      /> */}
      <pointLight
        intensity={15.729}
        decay={2}
        color="#77bcff"
        position={[0, 2, -2.99]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <group position={[0.257, 0, -2.983]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Black_LightUpper_Black-Upper_0006"].geometry}
            material={materials["Black-Upper.001"]}
            position={[-226.264, 508.734, 303.999]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Emissive_Red_Emissive-Red_0005"].geometry}
            material={materials["Emissive-Red.001"]}
            position={[4.632, 438.369, 303.999]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Light_Upper_Light-Upper_0006"].geometry}
            material={materials["Light-Upper.001"]}
            position={[-461.792, 451.184, 32.134]}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Supports001_M_Supports_0009.geometry}
        material={materials["M_Supports.002"]}
        position={[0.287, 14.419, 38.277]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[5.528, 5.703, 7.922]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Supports002_M_Supports_0009.geometry}
        material={materials["M_Supports.002"]}
        position={[0.287, 14.419, 26.871]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[5.528, 5.703, 7.922]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Supports_M_Supports_0009.geometry}
        material={materials["M_Supports.002"]}
        position={[0.287, 14.419, 49.683]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[5.528, 5.703, 7.922]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall001_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[-5.241, 6.497, 49.683]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall002_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[-5.241, 6.497, 38.277]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall004_M_Wall_0001.geometry}
        material={materials["M_Wall.003"]}
        position={[-5.241, 6.497, 15.464]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-27.639, -28.515, -39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall004_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[5.815, 6.497, 15.464]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall005_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[5.815, 6.497, 26.871]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall006_M_Wall_0009.geometry}
        material={materials["M_Wall.003"]}
        position={[5.815, 6.497, 38.277]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall007_M_Wall_0010.geometry}
        material={materials["M_Wall.003"]}
        position={[5.815, 6.497, 49.683]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[27.639, 28.515, 39.609]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_M_Wall_0010.geometry}
        material={materials["M_Wall.003"]}
        position={[-5.241, 6.497, 61.089]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[27.639, 28.515, 39.609]}
      />
    </group>
  );
}